### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by demtaric** [mage2tv/issues#56] opened 2019-09-19 07:09 UTC
I have tried Safari Version 12.1.2 (14607.3.9) and Chrome Version 76.0.3809.132
In responce:
```
URL: https://www.mage2.tv/api/user-session
Status: 500 No reader function for tag object
```

**Comment by Vinai** [comment] 2019-09-19 07:13
Hi @demtaric, thanks for your report!
Are you logging in with username or email or github oauth?

**Comment by Vinai** [comment] 2019-09-19 07:15
No worries, I've reproduced the issue, will update this thread when the problem is resolved!

**Comment by Vinai** [comment] 2019-09-19 10:15
A fix has been deployed, you should be able to log in again now. Sorry for the inconvenience!

**Closed as completed by Vinai** 2019-09-19 10:15 UTC
Labels: bug
